name: SegmentedMNLDiscreteChoiceModel

model_type: segmented_discretechoice

segmentation_col: income_3_tenure

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- residential_units > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 100

estimation_sample_size: null

prediction_sample_size: null

default_config:
    model_expression: ln_dist_rail + ln_avg_unit_price_zone + median_age_of_head +
        median_yearbuilt_post_1990 + percent_renter_hh_in_zone + multifamily + townhome
        + jobs_within_45min

models:
    1:
        fit_parameters:
            Coefficient:
                jobs_within_45min: 3.775804971525647e-08
                ln_avg_unit_price_zone: 0.030205409274651172
                ln_dist_rail: -3.234816790577229e-06
                median_age_of_head: -0.0455921021603338
                median_yearbuilt_post_1990: 0.16976995071215376
                multifamily: 1.8985853314682999
                percent_hh_with_child_x_hh_with_child: -7.380398088332255e-06
                percent_renter_hh_in_zone: -0.006835112008024204
                townhome: 1.2926502974992253
            Std. Error:
                jobs_within_45min: 4.145489994539023e-07
                ln_avg_unit_price_zone: 0.03650707363195327
                ln_dist_rail: 2.197197140336396e-06
                median_age_of_head: 0.010628631441543027
                median_yearbuilt_post_1990: 1.0788727348830482
                multifamily: 0.16186445667208854
                percent_hh_with_child_x_hh_with_child: 2.1448871743163154e-06
                percent_renter_hh_in_zone: 0.005431600626816389
                townhome: 0.23322438883873553
            T-Score:
                jobs_within_45min: 0.09108223579117612
                ln_avg_unit_price_zone: 0.8273851138869021
                ln_dist_rail: -1.4722469509868246
                median_age_of_head: -4.289555283865869
                median_yearbuilt_post_1990: 0.15735864409490072
                multifamily: 11.729476442839639
                percent_hh_with_child_x_hh_with_child: -3.440926020122603
                percent_renter_hh_in_zone: -1.2583973818469882
                townhome: 5.542517675512214
        fitted: true
        log_likelihoods:
            convergence: -961.920796834048
            'null': -1059.189142777258
            ratio: 0.09183283892824512
        model_expression: ln_dist_rail + ln_avg_unit_price_zone + median_age_of_head
            + median_yearbuilt_post_1990 + percent_hh_with_child_x_hh_with_child +
            percent_renter_hh_in_zone +  townhome + multifamily + jobs_within_45min
        name: 1
    2:
        fit_parameters:
            Coefficient:
                income5xlt_x_avg_unit_price_zone: 6.881141485390589e-13
                ln_dist_rail: -2.1170246702018794e-06
                ln_income_x_average_resunit_size: 1.2384587027790636e-06
                median_age_of_head: -1.1809297817025053e-06
                median_yearbuilt_post_1990: -1.313173745890635e-08
                median_yearbuilt_pre_1950: -4.103652777418656e-09
                multifamily: 1.151477771856513e-06
                percent_hh_with_child_x_hh_with_child: -1.3768349386754266e-06
                percent_renter_hh_in_zone: 1.1812501546524704e-06
                wkrs_hhs_x_ln_jobs_within_30min: 1.2000934661628056e-06
            Std. Error:
                income5xlt_x_avg_unit_price_zone: 1.143864985887937e-12
                ln_dist_rail: 1.268657307274543e-06
                ln_income_x_average_resunit_size: 8.240600265796425e-06
                median_age_of_head: 0.0037538203539368587
                median_yearbuilt_post_1990: 15.02911281292439
                median_yearbuilt_pre_1950: 28.554423896921914
                multifamily: 0.1776152283949206
                percent_hh_with_child_x_hh_with_child: 1.1500735295616409e-06
                percent_renter_hh_in_zone: 0.00336761234759805
                wkrs_hhs_x_ln_jobs_within_30min: 0.0003796984533774855
            T-Score:
                income5xlt_x_avg_unit_price_zone: 0.6015693784043081
                ln_dist_rail: -1.6687127863945264
                ln_income_x_average_resunit_size: 0.1502874381517365
                median_age_of_head: -0.0003145941122259601
                median_yearbuilt_post_1990: -8.737533360993618e-10
                median_yearbuilt_pre_1950: -1.4371338018348246e-10
                multifamily: 6.482990125690386e-06
                percent_hh_with_child_x_hh_with_child: -1.1971712271303363
                percent_renter_hh_in_zone: 0.0003507678535194222
                wkrs_hhs_x_ln_jobs_within_30min: 0.0031606488135196764
        fitted: true
        log_likelihoods:
            convergence: -2118.8662085292076
            'null': -2122.9834557405065
            ratio: 0.001939368486441051
        model_expression: ln_dist_rail + income5xlt_x_avg_unit_price_zone + median_age_of_head
            + median_yearbuilt_post_1990 + median_yearbuilt_pre_1950 + percent_hh_with_child_x_hh_with_child
            + percent_renter_hh_in_zone + multifamily + ln_income_x_average_resunit_size
            + wkrs_hhs_x_ln_jobs_within_30min
        name: 2
    !!python/long '3':
        fit_parameters:
            Coefficient:
                jobs_within_45min: 1.2341755090720326e-08
                ln_avg_unit_price_zone: 0.034589798713938254
                ln_dist_rail: -3.752937253645688e-06
                median_age_of_head: -0.02520914716531201
                median_yearbuilt_post_1990: -0.0153211457244832
                multifamily: 0.1513097146962649
                percent_renter_hh_in_zone: 0.011114363375237642
                townhome: 0.31106321975460577
            Std. Error:
                jobs_within_45min: 4.57364421333272e-07
                ln_avg_unit_price_zone: 0.04318292426517844
                ln_dist_rail: 1.7708715772940375e-06
                median_age_of_head: 0.011991756574347003
                median_yearbuilt_post_1990: 27.1076686559104
                multifamily: 0.27822268005548945
                percent_renter_hh_in_zone: 0.004538258636923129
                townhome: 0.2799729241285789
            T-Score:
                jobs_within_45min: 0.02698451063321155
                ln_avg_unit_price_zone: 0.8010064001578177
                ln_dist_rail: -2.1192599744473433
                median_age_of_head: -2.102206378942006
                median_yearbuilt_post_1990: -0.0005651959937595986
                multifamily: 0.543843926261106
                percent_renter_hh_in_zone: 2.4490370127457113
                townhome: 1.1110475083360152
        fitted: true
        log_likelihoods:
            convergence: -1205.3944139629618
            'null': -1215.7649291008524
            ratio: 0.008530033141818216
        name: !!python/long '3'
    4:
        fit_parameters:
            Coefficient:
                allpurpose_agglosum_floor: 0.7624926064687805
                ln_dist_rail: 3.167946001951426e-06
                ln_emp_sector3_within_20min: -0.2154085103074419
                percent_hh_with_child_x_hh_with_child: -1.5687383828687167e-05
                percent_renter_hh_in_zone: -0.0077774557617434886
                percent_younghead_x_younghead: -2.6743977799645276e-05
            Std. Error:
                allpurpose_agglosum_floor: 0.0506346130097511
                ln_dist_rail: 1.778801739498772e-06
                ln_emp_sector3_within_20min: 0.06388503796449348
                percent_hh_with_child_x_hh_with_child: 2.95099333466481e-06
                percent_renter_hh_in_zone: 0.006591505333083393
                percent_younghead_x_younghead: 9.96670659177432e-05
            T-Score:
                allpurpose_agglosum_floor: 15.058722900122518
                ln_dist_rail: 1.7809438407925577
                ln_emp_sector3_within_20min: -3.371814702953817
                percent_hh_with_child_x_hh_with_child: -5.315967218363449
                percent_renter_hh_in_zone: -1.1799210299819827
                percent_younghead_x_younghead: -0.268333150508489
        fitted: true
        log_likelihoods:
            convergence: -933.6181638202592
            'null': -1100.6356744511506
            ratio: 0.15174640846906706
        model_expression: ln_dist_rail + percent_hh_with_child_x_hh_with_child + percent_renter_hh_in_zone
            +  + percent_younghead_x_younghead + ln_emp_sector3_within_20min + allpurpose_agglosum_floor
        name: 4
    !!python/long '5':
        fit_parameters:
            Coefficient:
                jobs_within_45min: 1.1319601790963824e-06
                ln_avg_unit_price_zone: -0.006834717195464508
                ln_dist_rail: 3.53130949207175e-06
                median_age_of_head: -0.04286324889540237
                median_yearbuilt_post_1990: -3.0
                multifamily: 2.8626204321784847
                percent_renter_hh_in_zone: 0.0002349741629869956
                townhome: 1.365003177707593
            Std. Error:
                jobs_within_45min: 5.004692213751734e-07
                ln_avg_unit_price_zone: 0.03458969354568712
                ln_dist_rail: 2.077904416810294e-06
                median_age_of_head: 0.010129025114229936
                median_yearbuilt_post_1990: 210.65330047566806
                multifamily: 0.15421448282732134
                percent_renter_hh_in_zone: 0.005260895110565466
                townhome: 0.2774925756122984
            T-Score:
                jobs_within_45min: 2.261797790453563
                ln_avg_unit_price_zone: -0.19759403726537808
                ln_dist_rail: 1.6994571374425964
                median_age_of_head: -4.231725009269174
                median_yearbuilt_post_1990: -0.014241409905402935
                multifamily: 18.56259139670979
                percent_renter_hh_in_zone: 0.04466429344221224
                townhome: 4.919061977408438
        fitted: true
        log_likelihoods:
            convergence: -767.3710365922637
            'null': -921.0340371976157
            ratio: 0.16683748308900148
        name: !!python/long '5'

fitted: true

choice_mode: aggregate

remove_alts: false

probability_mode: single_chooser
