name: Zonal ELCM Model

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 100

estimation_sample_size: null

prediction_sample_size: null

model_expression: ln_avg_nonres_unit_price_zone +nb_pop + nb_emp + ln_residential_unit_density_zone
    + ln_non_residential_sqft_zone +percent_sf

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        ln_avg_nonres_unit_price_zone: -0.021485405779408218
        ln_non_residential_sqft_zone: 0.12988894617475633
        ln_residential_unit_density_zone: 0.22816033323570037
        nb_emp: 5.692664633271416e-05
        nb_pop: 2.8247740772075044e-05
        percent_sf: 0.0031149526549549686
    Std. Error:
        ln_avg_nonres_unit_price_zone: 0.0019020076039747622
        ln_non_residential_sqft_zone: 0.0008189444694933799
        ln_residential_unit_density_zone: 0.0028932473217135775
        nb_emp: 6.582305293389502e-07
        nb_pop: 4.443775983338022e-07
        percent_sf: 5.9381627198450036e-05
    T-Score:
        ln_avg_nonres_unit_price_zone: -11.29617238885303
        ln_non_residential_sqft_zone: 158.60531576104174
        ln_residential_unit_density_zone: 78.8596023310473
        nb_emp: 86.48436041075857
        nb_pop: 63.56697744888626
        percent_sf: 52.45650552055391

probability_mode: full_product

log_likelihoods:
    convergence: -888673.3782202307
    'null': -922604.4002335244
    ratio: 0.03677743353999319
