name: Zonal ELCM Model

model_type: discretechoice

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: zone_id

sample_size: 100

estimation_sample_size: null

prediction_sample_size: null

model_expression: ln_avg_nonres_unit_price_zone +nb_pop + nb_emp + ln_residential_unit_density_zone
    + ln_non_residential_sqft_zone +percent_sf

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        ln_avg_nonres_unit_price_zone: -0.021264740330130243
        ln_non_residential_sqft_zone: 0.1297074752431142
        ln_residential_unit_density_zone: 0.22819959637090884
        nb_emp: 5.700194871214045e-05
        nb_pop: 2.824042583036923e-05
        percent_sf: 0.0030917307042542955
    Std. Error:
        ln_avg_nonres_unit_price_zone: 0.0019020462169712373
        ln_non_residential_sqft_zone: 0.0008189598811068646
        ln_residential_unit_density_zone: 0.002893263967048941
        nb_emp: 6.582625869532649e-07
        nb_pop: 4.4436801038354587e-07
        percent_sf: 5.9381511672383926e-05
    T-Score:
        ln_avg_nonres_unit_price_zone: -11.17992830058125
        ln_non_residential_sqft_zone: 158.38074396001934
        ln_residential_unit_density_zone: 78.87271917455458
        nb_emp: 86.59454424710826
        nb_pop: 63.55188755822942
        percent_sf: 52.06554392403825

probability_mode: single_chooser

log_likelihoods:
    convergence: -888665.0995937773
    'null': -922604.4002335244
    ratio: 0.03678640664531463
